install: 
  - "npm install -g firebase-tools"
  - "npm install"
language: node_js
node_js: 
  - "8"
script: 
  - "npm run test"
  - "npm run build"
  - "firebase deploy - project la-casa-hits - token $FIREBASE_TOKEN"