language: node_js
node_js:
  - "8"
script:
  - echo “Deploy!!”
install:
  - npm install -g firebase-tools
after_success:
  - npm run test
  - npm run build
  - firebase deploy - project projectId - token $FIREBASE_TOKEN
cache:
  directories:
    - "node_modules"
