language: node_js
node_js:
  - "8"
install:
  - npm install -g firebase-tools
script:
  - npm run test
  - npm run build
after_success:
  - firebase deploy - project projectId - token $FIREBASE_TOKEN
