language: node_js
node_js:
  - "8"
script:
  - echo “Deploy!!”
cache:
  directories:
    - "node_modules"
install:
  - npm install -g firebase-tools
  - npm run build
after_success:
  - firebase deploy - project projectId - token $FIREBASE_TOKEN
